<a href="https://colab.research.google.com/github/layalbaydoun/batch_1973/blob/main/ESportProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# **Read Tables Dota2 and Fornite**

In [ ]:
df_dota2 = pd.read_excel ('/content/1_Scrap - Player data_csv_v2.xlsx', sheet_name = 'Dota2')
df_dota2.head()

,rank,country,url_player,pseudo_player,surname_name,total_cash_prize,game,age,age_during_game,Last_year_pro_date,Last_year_earnings,year_before_last,year_before_last_earnings,perct_change
0,1.0,dk,https://www.esportsearnings.com/players/3304-n...,N0tail,Johan Sundstein,7172436.83,Dota 2,31.0,27,2021,214100.0,2020,75571.40,0.029850
1,2.0,fi,https://www.esportsearnings.com/players/3822-j...,JerAx,Jesse Vainikka,6486075.22,Dota 2,33.0,30,2022,16400.0,2020,548.76,0.002528
2,3.0,au,https://www.esportsearnings.com/players/30451-...,ana,Anathan Pham,6024411.96,Dota 2,25.0,22,2022,20000.0,2021,4000.00,0.003320
3,4.0,ru,https://www.esportsearnings.com/players/15855-...,Miposhka,Yaroslav Naidenov,6011771.49,Dota 2,27.0,27,2025,135000.0,2024,247319.40,0.022456
4,5.0,fr,https://www.esportsearnings.com/players/2811-c...,Ceb,SÃ©bastien Debs,5949442.73,Dota 2,33.0,33,2025,3600.0,2024,58500.00,0.000605

In [ ]:
df_fortnite = pd.read_excel ('/content/1_Scrap - Player data_csv_v2.xlsx', sheet_name = 'Fortnite')
df_fortnite.head()

,rank,country,url_player,pseudo_player,surname_name,total_cash_prize,game,age,age_during_game,Last_year_pro_date,Last_year_earnings,year_before_last,year_before_last_earnings,perct_change
0,1.0,us,https://www.esportsearnings.com/players/56483-...,Bugha,Kyle Giersdorf,3732258.38,Fortnite,22.0,22,2025,1400.0,2024,78608.33,0.000375
1,2.0,at,https://www.esportsearnings.com/players/59528-...,Aqua,David Wang,2192375.23,Fortnite,22.0,21,2024,3500.0,2023,1441.00,0.001596
2,3.0,us,https://www.esportsearnings.com/players/25047-...,psalm,Harrison Chang,1874588.80,Fortnite,30.0,26,2021,100.0,2020,5488.80,0.000053
3,4.0,us,https://www.esportsearnings.com/players/61948-...,EpikWhale,Shane Cotton,1838487.32,Fortnite,22.0,21,2024,51600.0,2023,66270.00,0.028067
4,5.0,dk,https://www.esportsearnings.com/players/83369-...,Anas,Anas El-Abd,1622990.05,Fortnite,22.0,21,2024,27212.5,2023,28244.55,0.016767

In [ ]:
df_dota2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   rank                       500 non-null    float64
 1   country                    500 non-null    object
 2   url_player                 500 non-null    object
 3   pseudo_player              500 non-null    object
 4   surname_name               500 non-null    object
 5   total_cash_prize           500 non-null    float64
 6   game                       500 non-null    object
 7   age                        387 non-null    float64
 8   age_during_game            500 non-null    int64
 9   Last_year_pro_date         500 non-null    int64
 10  Last_year_earnings         500 non-null    float64
 11  year_before_last           500 non-null    int64
 12  year_before_last_earnings  500 non-null    float64
 13  perct_change               500 non-null    float64
dtypes: float64(6), int64(3), object(5)
memory usage: 54.8+ KB

In [ ]:
df_fortnite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   rank                       500 non-null    float64
 1   country                    500 non-null    object
 2   url_player                 500 non-null    object
 3   pseudo_player              500 non-null    object
 4   surname_name               500 non-null    object
 5   total_cash_prize           500 non-null    float64
 6   game                       500 non-null    object
 7   age                        140 non-null    float64
 8   age_during_game            500 non-null    int64
 9   Last_year_pro_date         500 non-null    int64
 10  Last_year_earnings         500 non-null    float64
 11  year_before_last           487 non-null    object
 12  year_before_last_earnings  500 non-null    float64
 13  perct_change               500 non-null    float64
dtypes: float64(6), int64(2), object(6)
memory usage: 54.8+ KB

# Math Aggregation

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)

df_dota2.describe()

,rank,total_cash_prize,age,age_during_game,Last_year_pro_date,Last_year_earnings,year_before_last,year_before_last_earnings,perct_change
count,500.00,500.00,387.00,500.00,500.00,500.00,500.00,500.00,500.00
mean,250.50,713640.75,28.57,20.01,2022.90,27098.18,2021.66,64545.76,0.09
std,144.48,1172023.91,4.10,12.61,2.49,56962.66,2.71,127493.27,0.15
min,1.00,43411.97,20.00,-13.00,2012.00,15.00,2011.00,58.33,0.00
25%,125.75,82465.48,26.00,21.00,2022.00,2509.70,2020.00,7180.62,0.01
50%,250.50,228290.83,28.00,25.00,2024.00,7553.50,2023.00,18518.17,0.03
75%,375.25,737695.17,32.00,28.00,2025.00,20537.50,2024.00,52081.21,0.11
max,500.00,7172436.83,40.00,39.00,2025.00,640485.00,2024.00,746600.00,0.91

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)

df_fortnite.describe()

,rank,total_cash_prize,age,age_during_game,Last_year_pro_date,Last_year_earnings,year_before_last_earnings,perct_change
count,500.00,500.00,140.00,500.00,500.00,500.00,500.00,500.00
mean,250.50,228546.42,22.69,3.82,2022.47,16468.99,52190.16,0.13
std,144.48,326208.18,4.14,11.04,1.98,37300.91,89933.55,0.26
min,1.00,58215.00,16.00,-7.00,2018.00,0.00,100.00,0.00
25%,125.75,75890.00,20.00,-4.00,2021.00,1200.00,6125.00,0.01
50%,250.50,113703.76,21.50,-1.00,2023.00,3781.25,21750.00,0.03
75%,375.25,221843.93,25.00,18.00,2024.00,12318.75,67352.50,0.10
max,500.00,3732258.38,36.00,32.00,2025.00,341325.00,1180543.33,1.00

In [ ]:
df_dota2.isnull().sum()

rank                           0
country                        0
url_player                     0
pseudo_player                  0
surname_name                   0
total_cash_prize               0
game                           0
age                          113
age_during_game                0
Last_year_pro_date             0
Last_year_earnings             0
year_before_last               0
year_before_last_earnings      0
perct_change                   0
dtype: int64

In [ ]:
df_fortnite.isnull().sum()

rank                           0
country                        0
url_player                     0
pseudo_player                  0
surname_name                   0
total_cash_prize               0
game                           0
age                          360
age_during_game                0
Last_year_pro_date             0
Last_year_earnings             0
year_before_last              13
year_before_last_earnings      0
perct_change                   0
dtype: int64

In [ ]:
print(df_dota2['game'].unique())

['Dota 2']

# **Top 10 Countries**

In [ ]:
top_countries_dota2 = df_dota2[df_dota2['game'] == 'Dota 2'] \
    .groupby('country')['total_cash_prize'] \
    .sum() \
    .sort_values(ascending=False)

# Display the top countries
print(top_countries_dota2.head(10))

country
cn   83381050.69
ru   38654143.27
ua   22426102.42
se   18993538.94
us   17877216.96
fi   17344431.21
dk   14572395.14
my   13670255.33
de   11436531.57
ph   11067427.38
Name: total_cash_prize, dtype: float64

In [ ]:
top_countries_fortnite = df_fortnite[df_fortnite['game'] == 'Fortnite'] \
    .groupby('country')['total_cash_prize'] \
    .sum() \
    .sort_values(ascending=False)

# Display the top countries
print(top_countries_fortnite.head(10))

country
us   37273824.06
ca    7555773.43
gb    6660592.86
dk    6282371.66
fr    5330587.38
pl    4476385.98
de    4158152.12
br    3943988.67
se    3824536.71
at    3555896.69
Name: total_cash_prize, dtype: float64

# **Full Country Name**

In [ ]:
!pip install pycountry

Collecting pycountry
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 36.9 MB/s eta 0:00:00
Installing collected packages: pycountry
Successfully installed pycountry-24.6.1

In [ ]:
import pycountry

# Example: your original DataFrame
# df_dota2 = pd.DataFrame({'country': ['us', 'cn', 'ru', ...]})

# Step 1: Create a function to map abbreviations to full names
def get_country_name(code):
    try:
        return pycountry.countries.get(alpha_2=code.upper()).name
    except:
        return 'Unknown'

# Step 2: Apply the function to the 'country' column
df_dota2['country_full'] = df_dota2['country'].apply(get_country_name)

In [ ]:
def get_country_name(code):
    try:
        return pycountry.countries.get(alpha_2=code.upper()).name
    except:
        return 'Unknown'

# Step 2: Apply the function to the 'country' column
df_fortnite['country_full'] = df_fortnite['country'].apply(get_country_name)

In [ ]:
top_countries_dota2 = df_dota2[df_dota2['game'] == 'Dota 2'] \
    .groupby('country_full')['total_cash_prize'] \
    .sum() \
    .sort_values(ascending=False)

# Display the top countries
print(top_countries_dota2.head(10))

country_full
China                83381050.69
Russian Federation   38654143.27
Ukraine              22426102.42
Sweden               18993538.94
United States        17877216.96
Finland              17344431.21
Denmark              14572395.14
Malaysia             13670255.33
Germany              11436531.57
Philippines          11067427.38
Name: total_cash_prize, dtype: float64

In [ ]:
top_countries_fortnite = df_fortnite[df_fortnite['game'] == 'Fortnite'] \
    .groupby('country_full')['total_cash_prize'] \
    .sum() \
    .sort_values(ascending=False)

# Display the top countries
print(top_countries_fortnite.head(10))

country_full
United States    37273824.06
Canada            7555773.43
United Kingdom    6660592.86
Denmark           6282371.66
France            5330587.38
Poland            4476385.98
Germany           4158152.12
Brazil            3943988.67
Sweden            3824536.71
Austria           3555896.69
Name: total_cash_prize, dtype: float64

# Plotting Top Countries by Total Earnings

In [ ]:
# Convert to DataFrame for plotting
top_countries_df = top_countries_dota2.head(10).reset_index()

fig = px.bar(
    top_countries_df,
    x='total_cash_prize',
    y='country_full',
    orientation='h',
    title='Top 10 Countries by Total Dota2 Earnings',
    labels={'total_cash_prize': 'Total Cash Prize (USD)', 'country_full': 'Country'},
    text='total_cash_prize'
)

fig.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

In [ ]:
# Convert to DataFrame for plotting
top_countries_df = top_countries_fortnite.head(10).reset_index()

fig = px.bar(
    top_countries_df,
    x='total_cash_prize',
    y='country_full',
    orientation='h',
    title='Top 10 Countries by Total Fortnite Earnings',
    labels={'total_cash_prize': 'Total Cash Prize (USD)', 'country_full': 'Country'},
    text='total_cash_prize'
)

fig.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

# **Count of Players per Country (Dota2 and Fortnite):**

In [ ]:
# Count players per country for each game
dota2_players_by_country = df_dota2[df_dota2['game'] == 'Dota 2'] \
    .groupby('country_full')['pseudo_player'] \
    .count() \
    .sort_values(ascending=False) \
    .reset_index() \
    .rename(columns={'pseudo_player': 'player_count'})
print(dota2_players_by_country)

                        country_full  player_count
0                              China           111
1                 Russian Federation            58
2                        Philippines            36
3                               Peru            32
4                            Ukraine            28
5                           Malaysia            25
6                      United States            23
7                             Sweden            20
8                             Brazil            13
9                            Germany            12
10                           Belarus            10
11                            Canada            10
12                           Denmark            10
13                         Indonesia             9
14                Korea, Republic of             8
15                            Greece             7
16                         Singapore             7
17                          Thailand             6
18                        Kazakhstan             6
19                       Netherlands             5
20                          Bulgaria             5
21                           Finland             4
22                            Israel             4
23                          Mongolia             4
24   Bolivia, Plurinational State of             3
25                           Czechia             3
26                           Romania             3
27                           Lebanon             3
28                        Kyrgyzstan             3
29                            Jordan             3
30                         Australia             2
31                         Argentina             2
32                            Poland             2
33                          Pakistan             2
34                           Georgia             2
35                           Austria             1
36                           Belgium             1
37                           Armenia             1
38         Iran, Islamic Republic of             1
39                            France             1
40                           Estonia             1
41            Bosnia and Herzegovina             1
42                            Mexico             1
43                             Macao             1
44  Lao People's Democratic Republic             1
45              Moldova, Republic of             1
46                            Norway             1
47                   North Macedonia             1
48                         Nicaragua             1
49                            Serbia             1
50                          Slovakia             1
51                    United Kingdom             1
52                        Uzbekistan             1
53                          Viet Nam             1

In [ ]:
fig = px.bar(
    dota2_players_by_country.head(10),
    x='player_count',
    y='country_full',
    orientation='h',
    title='Top 10 Countries by Dota2 Player Count',
    labels={'player_count': 'Number of Players', 'country_full': 'Country'},
    text='player_count'
)

fig.update_traces(textposition='outside')
fig.update_layout(yaxis={'categoryorder': 'total ascending'})
fig.show()

In [ ]:
fortnite_players_by_country = df_fortnite[df_fortnite['game'] == 'Fortnite'] \
    .groupby('country_full')['pseudo_player'] \
    .count() \
    .sort_values(ascending=False) \
    .reset_index() \
    .rename(columns={'pseudo_player': 'player_count'})
print(fortnite_players_by_country)

              country_full  player_count
0            United States           149
1                   Brazil            30
2                   France            28
3                   Canada            26
4           United Kingdom            23
5                    Japan            21
6                  Denmark            21
7                   Sweden            21
8                Australia            20
9                  Germany            20
10                  Poland            14
11      Russian Federation            14
12             Netherlands            10
13            Saudi Arabia             9
14               Argentina             7
15                  Mexico             7
16             Switzerland             7
17      Korea, Republic of             7
18             New Zealand             6
19                   Spain             5
20                Slovenia             5
21                  Norway             5
22                 Belgium             4
23                 Austria             4
24                 Finland             3
25                 Ukraine             3
26                 Türkiye             3
27                   China             3
28                 Belarus             3
29                 Bahrain             2
30                 Czechia             2
31                  Serbia             2
32                  Latvia             2
33                 Croatia             1
34  Bosnia and Herzegovina             1
35      Dominican Republic             1
36                    Cuba             1
37                   Italy             1
38                   India             1
39               Lithuania             1
40                  Kuwait             1
41                 Ireland             1
42                 Estonia             1
43               Hong Kong             1
44                 Romania             1
45                Pakistan             1
46             Philippines             1

In [ ]:
fig = px.bar(
    fortnite_players_by_country.head(10),
    x='player_count',
    y='country_full',
    orientation='h',
    title='Top 10 Countries by Fortnite Player Count',
    labels={'player_count': 'Number of Players', 'country_full': 'Country'},
    text='player_count'
)

fig.update_traces(textposition='outside')
fig.update_layout(yaxis={'categoryorder': 'total ascending'})
fig.show()

**Age Null Values**

In [ ]:
# NaN values
df_dota2.isnull().sum()

rank                           0
country                        0
url_player                     0
pseudo_player                  0
surname_name                   0
total_cash_prize               0
game                           0
age                          113
age_during_game                0
Last_year_pro_date             0
Last_year_earnings             0
year_before_last               0
year_before_last_earnings      0
perct_change                   0
country_full                   0
dtype: int64

In [ ]:
# NaN values
df_fortnite.isnull().sum()

rank                           0
country                        0
url_player                     0
pseudo_player                  0
surname_name                   0
total_cash_prize               0
game                           0
age                          360
age_during_game                0
Last_year_pro_date             0
Last_year_earnings             0
year_before_last              13
year_before_last_earnings      0
perct_change                   0
country_full                   0
dtype: int64

# **Plot Age By Country**

In [ ]:
# Filter out rows with missing or unrealistic ages if needed
df_dota2_clean = df_dota2[df_dota2['age_during_game'].notna() & (df_dota2['age_during_game'] > 0)]

# Box plot
fig = px.box(
    df_dota2_clean,
    x='country_full',
    y='age_during_game',
    title='Age Distribution of Dota2 Players by Country',
    labels={'age': 'Player Age', 'country_full': 'Country'}
)

# Improve layout
fig.update_layout(xaxis_tickangle=45)
fig.show()

In [ ]:
df_fortnite_clean = df_fortnite[df_fortnite['age_during_game'].notna() & (df_fortnite['age_during_game'] > 0)]

# Box plot
fig = px.box(
    df_fortnite_clean,
    x='country_full',
    y='age_during_game',
    title='Age Distribution of Fortnite Players by Country',
    labels={'age': 'Player Age', 'country_full': 'Country'}
)

# Improve layout
fig.update_layout(xaxis_tickangle=45)
fig.show()

In [ ]:
df_dota2_clean = df_dota2[df_dota2['age_during_game'].notna() & (df_dota2['age_during_game'] > 0)]

# Scatter plot
fig = px.strip(
    df_dota2_clean,
    x='country_full',
    y='age_during_game',
    title='Scatter Plot of Player Ages by Country (Dota2)',
    labels={'country_full': 'Country', 'age': 'Player Age'},
    stripmode='overlay',  # Compact points on the same line
)

fig.update_traces(jitter=0.35, marker_opacity=0.6)
fig.update_layout(xaxis_tickangle=45)
fig.show()

# **Filter By The Year 2024 and 2025 For Active Players**

In [ ]:
# Filter Dota 2 players with activity in 2024 or 2025
df_filter = df_dota2[
    (df_dota2['Last_year_pro_date'].isin([2024, 2025])) &
    (df_dota2['game'] == 'Dota 2')
]

# Keep only the relevant columns
df_filter = df_filter[['total_cash_prize', 'game', 'Last_year_pro_date', 'Last_year_earnings', 'perct_change']]

# Display the result
df_filter

,total_cash_prize,game,Last_year_pro_date,Last_year_earnings,perct_change
3,6011771.49,Dota 2,2025,135000.00,0.02
4,5949442.73,Dota 2,2025,3600.00,0.00
5,5898810.60,Dota 2,2024,176136.07,0.03
6,5724111.07,Dota 2,2025,135000.00,0.02
7,5716736.05,Dota 2,2025,135000.00,0.02
...,...,...,...,...,...
489,46342.80,Dota 2,2024,42342.80,0.91
490,46099.44,Dota 2,2024,26066.67,0.57
492,45495.83,Dota 2,2025,2000.00,0.04
495,44567.50,Dota 2,2024,10600.00,0.24
499,43411.97,Dota 2,2024,19598.20,0.45

In [ ]:
# Filter Fortnite players with activity in 2024 or 2025
df_filter = df_fortnite[
    (df_fortnite['Last_year_pro_date'].isin([2024, 2025])) &
    (df_fortnite['game'] == 'Fortnite')
]

# Keep only the relevant columns
df_filter = df_filter[['total_cash_prize', 'game', 'Last_year_pro_date', 'Last_year_earnings', 'perct_change']]

# Display the result
df_filter

,total_cash_prize,game,Last_year_pro_date,Last_year_earnings,perct_change
0,3732258.38,Fortnite,2025,1400.00,0.00
1,2192375.23,Fortnite,2024,3500.00,0.00
3,1838487.32,Fortnite,2024,51600.00,0.03
4,1622990.05,Fortnite,2024,27212.50,0.02
6,1513689.20,Fortnite,2025,13270.00,0.01
...,...,...,...,...,...
477,60825.00,Fortnite,2024,3750.00,0.06
482,60432.00,Fortnite,2025,300.00,0.00
488,59798.83,Fortnite,2025,3910.00,0.07
491,59162.50,Fortnite,2024,34900.00,0.59
498,58413.80,Fortnite,2024,125.00,0.00

**Filter by Last year pro date 2024 and 2025 / Year before last == 2024**

In [ ]:
df_filter = df_dota2[
    (df_dota2['Last_year_pro_date'].isin([2024, 2025])) &
    (df_dota2['year_before_last'] == 2024) &
    (df_dota2['game'] == 'Dota 2')
]

# Keep only relevant columns
df_filter = df_filter[
    ['total_cash_prize', 'game', 'Last_year_pro_date', 'Last_year_earnings', 'perct_change', 'year_before_last']
]
df_filter

,total_cash_prize,game,Last_year_pro_date,Last_year_earnings,perct_change,year_before_last
3,6011771.49,Dota 2,2025,135000.00,0.02,2024
4,5949442.73,Dota 2,2025,3600.00,0.00,2024
6,5724111.07,Dota 2,2025,135000.00,0.02,2024
7,5716736.05,Dota 2,2025,135000.00,0.02,2024
8,5593899.05,Dota 2,2025,31000.00,0.01,2024
...,...,...,...,...,...,...
474,49014.26,Dota 2,2025,1500.00,0.03,2024
477,48617.74,Dota 2,2025,13000.00,0.27,2024
478,48113.05,Dota 2,2025,7000.00,0.15,2024
484,47756.00,Dota 2,2025,1500.00,0.03,2024
492,45495.83,Dota 2,2025,2000.00,0.04,2024

In [ ]:
df_filter = df_fortnite[
    (df_fortnite['Last_year_pro_date'].isin([2024, 2025])) &
    (df_fortnite['year_before_last'] == 2024) &
    (df_fortnite['game'] == 'Fortnite')
]

# Keep only relevant columns
df_filter = df_filter[
    ['total_cash_prize', 'game', 'Last_year_pro_date', 'Last_year_earnings', 'perct_change', 'year_before_last']
]
df_filter

,total_cash_prize,game,Last_year_pro_date,Last_year_earnings,perct_change,year_before_last
0,3732258.38,Fortnite,2025,1400.00,0.00,2024
6,1513689.20,Fortnite,2025,13270.00,0.01,2024
8,1330476.44,Fortnite,2025,3750.00,0.00,2024
10,1223513.70,Fortnite,2025,9625.00,0.01,2024
14,1204712.10,Fortnite,2025,4267.00,0.00,2024
...,...,...,...,...,...,...
422,67639.85,Fortnite,2025,1200.00,0.02,2024
440,65780.00,Fortnite,2025,4630.00,0.07,2024
471,61691.92,Fortnite,2025,1690.00,0.03,2024
482,60432.00,Fortnite,2025,300.00,0.00,2024
488,59798.83,Fortnite,2025,3910.00,0.07,2024

# **Read Sheet Tournaments Dota and Fortnite**

In [ ]:
df_tournament = pd.read_excel ('/content/1_Scrap - Player data_csv_v2.xlsx', sheet_name = 'Dota 2 - Fortnite')
df_tournament.head()

,rank,link,?,link_2,name,date,cash_prize,nb_teams,nb_players,link_2_here,Filters,game
0,1.00,https://www.esportsearnings.com/events/9018-th...,Â»,https://www.esportsearnings.com/tournaments/49...,The International 2021,2021,"$40,018,400.00",18 Teams,90 Players,1,NaN,Dota 2
1,2.00,https://www.esportsearnings.com/events/7214-th...,Â»,https://www.esportsearnings.com/tournaments/37...,The International 2019,2019,"$34,330,069.00",18 Teams,90 Players,1,NaN,Dota 2
2,3.00,https://www.esportsearnings.com/events/5819-th...,Â»,https://www.esportsearnings.com/tournaments/29...,The International 2018,2018,"$25,532,177.00",18 Teams,90 Players,1,NaN,Dota 2
3,4.00,https://www.esportsearnings.com/events/4970-th...,Â»,https://www.esportsearnings.com/tournaments/24...,The International 2017,2017,"$24,687,919.00",18 Teams,90 Players,1,NaN,Dota 2
4,5.00,https://www.esportsearnings.com/events/4038-th...,Â»,https://www.esportsearnings.com/tournaments/19...,The International 2016,2016,"$20,770,460.00",16 Teams,80 Players,1,NaN,Dota 2

In [ ]:
df_tournament.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rank         1000 non-null   float64
 1   link         1000 non-null   object
 2   ?            946 non-null    object
 3   link_2       946 non-null    object
 4   name         1000 non-null   object
 5   date         1000 non-null   int64
 6   cash_prize   1000 non-null   object
 7   nb_teams     499 non-null    object
 8   nb_players   1000 non-null   object
 9   link_2_here  1000 non-null   int64
 10  Filters      518 non-null    object
 11  game         1000 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 93.9+ KB

In [ ]:
df_tournament = df_tournament.drop(columns=['Filters', 'link', 'link_2', 'link_2_here','?'], errors='ignore')

In [ ]:
print(df_tournament.columns.tolist())

['rank', 'name', 'date', 'cash_prize', 'nb_teams', 'nb_players', 'game']

In [ ]:
df_tournament
# 1000 rows

,rank,name,date,cash_prize,nb_teams,nb_players,game
0,1.00,The International 2021,2021,"$40,018,400.00",18 Teams,90 Players,Dota 2
1,2.00,The International 2019,2019,"$34,330,069.00",18 Teams,90 Players,Dota 2
2,3.00,The International 2018,2018,"$25,532,177.00",18 Teams,90 Players,Dota 2
3,4.00,The International 2017,2017,"$24,687,919.00",18 Teams,90 Players,Dota 2
4,5.00,The International 2016,2016,"$20,770,460.00",16 Teams,80 Players,Dota 2
...,...,...,...,...,...,...,...
995,496.00,Chapter 2 Season 2: Contender Duo Cash Cup - W...,2020,"$50,000.00",NaN,64 Players,Fortnite
996,497.00,Chapter 2 Season 2: Contender Duo Cash Cup - W...,2020,"$50,000.00",NaN,97 Players,Fortnite
997,498.00,Chapter 2 Season 2: Contender Duo Cash Cup - W...,2020,"$50,000.00",NaN,28 Players,Fortnite
998,499.00,Chapter 2 Season 2: Contender Duo Cash Cup - W...,2020,"$50,000.00",NaN,96 Players,Fortnite
999,500.00,Chapter 2 Season 2: Contender Duo Cash Cup - W...,2020,"$50,000.00",NaN,92 Players,Fortnite

In [ ]:
# Filter for dates between 2022 and 2025
df_tournament_filter = df_tournament[(df_tournament['date'] >= 2022) & (df_tournament['date'] <= 2025)]

# Preview the result
df_tournament_filter

#283 rows

,rank,name,date,cash_prize,nb_teams,nb_players,game
5,6.00,The International 2022,2022,"$18,930,256.00",20 Teams,100 Players,Dota 2
7,8.00,Riyadh Masters 2023,2023,"$15,120,000.00",32 Teams,102 Players,Dota 2
9,10.00,Riyadh Masters 2024,2024,"$5,050,000.00",21 Teams,100 Players,Dota 2
10,11.00,Riyadh Masters 2022,2022,"$4,200,000.00",15 Teams,50 Players,Dota 2
11,12.00,The International 2023,2023,"$3,380,904.00",20 Teams,100 Players,Dota 2
...,...,...,...,...,...,...,...
978,479.00,Chapter 4 Season 1: Elite Cup Finals - Week 4:...,2023,"$54,100.00",NaN,80 Players,Fortnite
979,480.00,Chapter 4 Season 1: Elite Cup Finals - Week 5:...,2023,"$54,100.00",NaN,50 Players,Fortnite
980,481.00,Chapter 5 Season 4: PlayStation SypherPK Cup: NA,2024,"$52,400.00",NaN,11 Players,Fortnite
981,482.00,Twitch Rivals - Creative Gauntlet 1,2023,"$50,116.00",NaN,32 Players,Fortnite
986,487.00,Australian Open: Summer Smash 2023,2023,"$50,000.00",NaN,11 Players,Fortnite

**Cleaning data**

In [ ]:
df_tournament_filter['nb_teams'] = (
    df_tournament_filter['nb_teams']
    .astype(str)  # Ensure all values are strings
    .str.replace(r' Team[s]?$', '', regex=True)  # Handle both "Team" and "Teams"
    .replace('nan', None)
    .pipe(pd.to_numeric, errors='coerce')  # Convert to numbers
    .fillna(0)
    .astype(int)
)

<ipython-input-40-bc8ba72c1bdb>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_tournament_filter['cash_prize'] = (
    df_tournament_filter['cash_prize']
    .astype(str)                              # Ensure all values are strings
    .str.replace('[\$,]', '', regex=True)     # Remove $ and commas
    .replace('nan', None)                     # Optional: Handle "nan" strings
    .pipe(pd.to_numeric, errors='coerce')     # Convert to float
    .fillna(0)                                 # Handle NaNs if needed
    .astype(int)
)

<ipython-input-41-cb40a156a193>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_tournament_filter['nb_players'] = (
    df_tournament_filter['nb_players']
    .astype(str)
    .str.replace(r' Player[s]?$', '', regex=True)  # Removes " Player" or " Players"
    .replace('nan', None)
    .pipe(pd.to_numeric, errors='coerce')
    .fillna(0)
    .astype(int)
)

<ipython-input-42-b2c8d4a597ed>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_tournament_filter.describe()

        rank    date  cash_prize  nb_teams  nb_players
count 283.00  283.00      283.00    283.00      283.00
mean  258.64 2023.05   457006.42      4.59       49.16
std   151.94    0.96  1529912.17      5.41       26.42
min     4.00 2022.00    50000.00      0.00        1.00
25%   161.00 2022.00    75000.00      0.00       31.00
50%   278.00 2023.00   100000.00      4.00       40.00
75%   377.00 2024.00   250000.00      8.00       60.00
max   496.00 2025.00 18930256.00     32.00      145.00

In [ ]:
df_tournament_filter.isnull().sum()

rank          0
name          0
date          0
cash_prize    0
nb_teams      0
nb_players    0
game          0
dtype: int64

In [ ]:
df_tournament_filter.info()

<class 'pandas.core.frame.DataFrame'>
Index: 283 entries, 5 to 986
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        283 non-null    float64
 1   name        283 non-null    object
 2   date        283 non-null    int64
 3   cash_prize  283 non-null    int64
 4   nb_teams    283 non-null    int64
 5   nb_players  283 non-null    int64
 6   game        283 non-null    object
dtypes: float64(1), int64(4), object(2)
memory usage: 17.7+ KB

In [ ]:
df_tournament_filter

,rank,name,date,cash_prize,nb_teams,nb_players,game
5,6.00,The International 2022,2022,18930256,20,100,Dota 2
7,8.00,Riyadh Masters 2023,2023,15120000,32,102,Dota 2
9,10.00,Riyadh Masters 2024,2024,5050000,21,100,Dota 2
10,11.00,Riyadh Masters 2022,2022,4200000,15,50,Dota 2
11,12.00,The International 2023,2023,3380904,20,100,Dota 2
...,...,...,...,...,...,...,...
978,479.00,Chapter 4 Season 1: Elite Cup Finals - Week 4:...,2023,54100,0,80,Fortnite
979,480.00,Chapter 4 Season 1: Elite Cup Finals - Week 5:...,2023,54100,0,50,Fortnite
980,481.00,Chapter 5 Season 4: PlayStation SypherPK Cup: NA,2024,52400,0,11,Fortnite
981,482.00,Twitch Rivals - Creative Gauntlet 1,2023,50116,0,32,Fortnite
986,487.00,Australian Open: Summer Smash 2023,2023,50000,0,11,Fortnite

**📊 Total Cash Prize per Year**

In [ ]:
df_tournament_filter['date'] = df_tournament_filter['date'].round().astype(int)

<ipython-input-47-767c1330ac4e>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_tournament_filter['date'] = df_tournament_filter['date'].astype(str)
fig = px.bar(
    df_tournament_filter.groupby('date')['cash_prize'].sum().reset_index(),
    x='date', y='cash_prize',
    title='Total Cash Prize by Year',
    labels={'cash_prize': 'Total Cash Prize ($)', 'date': 'Year'}
)
fig.show()

<ipython-input-48-e330175b597d>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**🎯 Cash Prize vs Number of Players**

In [ ]:
fig = px.scatter(
    df_tournament_filter,
    x='nb_players', y='cash_prize',
    size='cash_prize', color='date',
    hover_name='name',
    title='Cash Prize vs Number of Players'
)
fig.show()

**🥇 Top 10 Tournaments by Cash Prize**

In [ ]:
top10 = df_tournament_filter.nlargest(10, 'cash_prize')

fig = px.bar(
    top10,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Tournaments by Cash Prize',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig.update_layout(yaxis={'categoryorder': 'total ascending'})
fig.show()

**Top 10 Fortnite tournaments**

In [ ]:
# Top 10 Fortnite tournaments
top10_fortnite = df_tournament_filter[df_tournament_filter['game'] == 'Fortnite'] \
    .nlargest(10, 'cash_prize')

fig_fortnite = px.bar(
    top10_fortnite,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Fortnite Tournaments by Cash Prize',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_fortnite.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_fortnite.show()

**# Top 10 Dota 2 tournaments**

In [ ]:
top10_dota2 = df_tournament_filter[df_tournament_filter['game'] == 'Dota 2'] \
    .nlargest(10, 'cash_prize')

fig_dota2 = px.bar(
    top10_dota2,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Dota 2 Tournaments by Cash Prize',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_dota2.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_dota2.show()

In [ ]:
# First, convert the date column to datetime safely
df_tournament_filter['date'] = pd.to_datetime(df_tournament_filter['date'], errors='coerce')

# Extract year into a new column
df_tournament_filter['year'] = df_tournament_filter['date'].dt.year

<ipython-input-53-0a5286f42b14>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-53-0a5286f42b14>:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# **Cash Prize for Dota 2 during 2022-2023-2024-2025**

In [ ]:
top10_dota2_2022 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Dota 2') &
    (df_tournament_filter['year'] == 2022)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_dota2_2022 = px.bar(
    top10_dota2_2022,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Dota 2 Tournaments by Cash Prize in 2022',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_dota2_2022.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_dota2_2022.show()

In [ ]:
top10_dota2_2023 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Dota 2') &
    (df_tournament_filter['year'] == 2023)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_dota2_2023 = px.bar(
    top10_dota2_2023,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Dota 2 Tournaments by Cash Prize in 2023',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_dota2_2023.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_dota2_2023.show()

In [ ]:
top10_dota2_2024 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Dota 2') &
    (df_tournament_filter['year'] == 2024)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_dota2_2024 = px.bar(
    top10_dota2_2024,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Dota 2 Tournaments by Cash Prize in 2024',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_dota2_2024.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_dota2_2024.show()

In [ ]:
top10_dota2_2025 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Dota 2') &
    (df_tournament_filter['year'] == 2025)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_dota2_2025 = px.bar(
    top10_dota2_2025,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Dota 2 Tournaments by Cash Prize in 2025',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_dota2_2025.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_dota2_2025.show()

# **Cash Prize for Fortnite during 2022-2023-2024-2025**

In [ ]:
top10_fortnite_2022 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Fortnite') &
    (df_tournament_filter['year'] == 2022)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_fortnite_2022 = px.bar(
    top10_fortnite_2022,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Fortnite Tournaments by Cash Prize in 2022',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_fortnite_2022.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_fortnite_2022.show()

In [ ]:
top10_fortnite_2023 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Fortnite') &
    (df_tournament_filter['year'] == 2023)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_fortnite_2023 = px.bar(
    top10_fortnite_2023,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Fortnite Tournaments by Cash Prize in 2023',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_fortnite_2023.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_fortnite_2023.show()

In [ ]:
top10_fortnite_2024 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Fortnite') &
    (df_tournament_filter['year'] == 2024)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_fortnite_2024 = px.bar(
    top10_fortnite_2024,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Fortnite Tournaments by Cash Prize in 2024',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_fortnite_2024.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_fortnite_2024.show()

In [ ]:
top10_fortnite_2025 = df_tournament_filter[
    (df_tournament_filter['game'] == 'Fortnite') &
    (df_tournament_filter['year'] == 2025)
].nlargest(10, 'cash_prize')

import plotly.express as px

fig_fortnite_2025 = px.bar(
    top10_fortnite_2025,
    x='cash_prize', y='name',
    orientation='h',
    title='Top 10 Fortnite Tournaments by Cash Prize in 2025',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament'},
)
fig_fortnite_2025.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_fortnite_2025.show()

# **Database tournament clean**

In [ ]:
df_tournament_clean = pd.read_excel('/content/database_tournament_clean.xlsx', sheet_name = 'Main')
df_tournament_clean.head()

,rank,link,link_2,name,date,cash_prize,nb_teams,nb_players,link_2_here,game
0,1,https://www.esportsearnings.com/events/5995-lo...,https://www.esportsearnings.com/tournaments/30...,LoL 2018 World Championship,2018,6450000.00,24 Teams,131 Players,1.00,League of Legends
1,2,https://www.esportsearnings.com/events/4241-20...,https://www.esportsearnings.com/tournaments/20...,LoL 2016 World Championship,2016,5070000.00,16 Teams,86 Players,1.00,League of Legends
2,3,https://www.esportsearnings.com/events/5156-20...,https://www.esportsearnings.com/tournaments/25...,LoL 2017 World Championship,2017,4946969.00,24 Teams,128 Players,1.00,League of Legends
3,4,https://www.esportsearnings.com/events/8304-lo...,https://www.esportsearnings.com/tournaments/43...,LoL 2020 World Championship,2020,2340000.00,25 Teams,113 Players,1.00,League of Legends
4,5,https://www.esportsearnings.com/events/7484-lo...,https://www.esportsearnings.com/tournaments/38...,LoL 2019 World Championship,2019,2225000.00,24 Teams,127 Players,1.00,League of Legends

In [ ]:
df_tournament_clean.drop(columns=['link','link_2','link_2_here'], inplace=True)

In [ ]:
df_tournament_clean.describe()

         rank    date  cash_prize
count 3600.00 3600.00     3600.00
mean   231.06 2020.79   225192.59
std    138.10    2.81  1335972.47
min      1.00 2011.00     4812.00
25%    113.00 2019.00    21600.00
50%    225.50 2021.00    52729.26
75%    343.00 2023.00   121200.00
max    500.00 2025.00 40018400.00

In [ ]:
df_tournament_clean.isnull().sum()

rank            0
name            0
date            0
cash_prize      0
nb_teams      540
nb_players      0
game            0
dtype: int64

In [ ]:
df_tournament_clean

,rank,name,date,cash_prize,nb_teams,nb_players,game
0,1,LoL 2018 World Championship,2018,6450000.00,24 Teams,131 Players,League of Legends
1,2,LoL 2016 World Championship,2016,5070000.00,16 Teams,86 Players,League of Legends
2,3,LoL 2017 World Championship,2017,4946969.00,24 Teams,128 Players,League of Legends
3,4,LoL 2020 World Championship,2020,2340000.00,25 Teams,113 Players,League of Legends
4,5,LoL 2019 World Championship,2019,2225000.00,24 Teams,127 Players,League of Legends
...,...,...,...,...,...,...,...
3595,496,RLCS Season X - Winter: The Grid EU - Week 3,2021,15000.00,4 Teams,12 Players,Rocket League
3596,497,RLCS Season X - Winter: The Grid EU - Week 4,2021,15000.00,4 Teams,12 Players,Rocket League
3597,498,RLCS Season X - Winter: The Grid NA - Week 1,2020,15000.00,4 Teams,12 Players,Rocket League
3598,499,RLCS Season X - Winter: The Grid NA - Week 2,2020,15000.00,4 Teams,12 Players,Rocket League
3599,500,RLCS Season X - Winter: The Grid NA - Week 3,2021,15000.00,4 Teams,12 Players,Rocket League

In [ ]:
df_tournament_clean['cash_prize'].max()

40018400.0

# **Evolution of Total Cash Prizes Over the Years By Game**

In [ ]:
# Ensure 'date' is numeric and treat it as 'year'
df_tournament_clean['year'] = pd.to_numeric(df_tournament_clean['date'], errors='coerce')

# Drop any rows with invalid years
df = df_tournament_clean.dropna(subset=['year'])

# Group by year and game, summing up the cash prize
cash_prize_evolution = df_tournament_clean.groupby(['year', 'game'])['cash_prize'].sum().reset_index()

# Create line chart
fig = px.line(
    cash_prize_evolution,
    x='year',
    y='cash_prize',
    color='game',
    markers=True,
    title='Evolution of Total Cash Prizes Over the Years by Game',
    labels={'cash_prize': 'Total Cash Prize ($)', 'year': 'Year'}
)

# Show every year on the x-axis
fig.update_layout(xaxis=dict(dtick=1))
fig.show()

In [ ]:
# Convert the 'date' column to datetime
df_tournament_clean['date'] = pd.to_numeric(df_tournament_clean['date'], errors='coerce')


# Filter for years 2022 to 2024
filtered_df = df_tournament_clean[df_tournament_clean['year'].isin([2022, 2023, 2024])]

# Get the sum cash prize per year and game
cash_prize_evolution = (
    filtered_df.groupby(['year', 'game'])['cash_prize']
    .sum()
    .reset_index()
)

# Create line chart
fig = px.line(
cash_prize_evolution,
    x='year',
    y='cash_prize',
    color='game',
    markers=True,
    title='Evolution of Total Cash Prizes (2022–2024) by Game',
    labels={'cash_prize': 'Total Cash Prize ($)', 'year': 'Year'}
)

fig.update_layout(xaxis=dict(dtick=1))
fig.show()

# **Top 50 tournaments by cash prize**

In [ ]:
# Get the top 50 tournaments by cash prize
top50_all_games = df_tournament_clean.nlargest(50, 'cash_prize')

# Create the bar chart
fig = px.bar(
    top50_all_games,
    x='cash_prize',
    y='name',
    color='game',
    orientation='h',
    title='Top 50 Tournaments by Cash Prize (All Games)',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament', 'game': 'Game'},
)

# Sort bars from highest to lowest
fig.update_layout(yaxis={'categoryorder': 'total ascending'})

fig.show()

# **Top 50 tournaments by cash prize from 2022 to 2024**

In [ ]:
# Make sure 'date' is in datetime format
df_tournament_clean['date'] = pd.to_numeric(df_tournament_clean['date'], errors='coerce')

# Filter for years 2022, 2023, and 2024
df_filtered = df_tournament_clean[
    df_tournament_clean['date'].isin([2022, 2023, 2024])
]

# Get the top 50 tournaments by cash prize from the filtered data
top50_filtered = df_filtered.nlargest(50, 'cash_prize')

# Plot
fig = px.bar(
    top50_filtered,
    x='cash_prize',
    y='name',
    color='game',
    orientation='h',
    title='Top 50 Tournaments by Cash Prize (2022–2024)',
    labels={'cash_prize': 'Cash Prize ($)', 'name': 'Tournament', 'game': 'Game'},
)

# Sort from highest to lowest
fig.update_layout(yaxis={'categoryorder': 'total ascending'})

fig.show()

# **Total Cash Prize By Year for all games**

In [ ]:
df_tournament_clean['date'] = pd.to_numeric(df_tournament_clean['date'], errors='coerce')
df_tournament_clean['date'] = df_tournament_clean['date']
fig = px.bar(
    df_tournament_clean.groupby('date')['cash_prize'].sum().reset_index(),
    x='date', y='cash_prize',
    title='Total Cash Prize by Year',
    labels={'cash_prize': 'Total Cash Prize ($)', 'date': 'Year'}
)
fig.show()

# **Player Database Clean**

In [ ]:
df_player_clean = pd.read_excel('/content/player_database_clean (1).xlsx')
df_player_clean

,rank,url_player,pseudo_player,surname_name,total_cash_prize,game,age,age_during_game,last_year_pro_date,last_year_earnings,year_before_last,year_before_last_earnings,last_year_to_total,year_before_to_total,country_full
0,1,https://www.esportsearnings.com/players/3304-n...,N0tail,Johan Sundstein,7172436.83,Dota 2,31.00,27.00,2021,214100.00,2020,75571.40,0.03,0.01,Denmark
1,2,https://www.esportsearnings.com/players/3822-j...,JerAx,Jesse Vainikka,6486075.22,Dota 2,33.00,30.00,2022,16400.00,2020,548.76,0.00,0.00,Finland
2,3,https://www.esportsearnings.com/players/30451-...,ana,Anathan Pham,6024411.96,Dota 2,25.00,22.00,2022,20000.00,2021,4000.00,0.00,0.00,Australia
3,4,https://www.esportsearnings.com/players/15855-...,Miposhka,Yaroslav Naidenov,6011771.49,Dota 2,27.00,27.00,2025,135000.00,2024,247319.40,0.02,0.04,Russian Federation
4,5,https://www.esportsearnings.com/players/2811-c...,Ceb,SÃ©bastien Debs,5949442.73,Dota 2,33.00,33.00,2025,3600.00,2024,58500.00,0.00,0.01,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,296,https://www.esportsearnings.com/players/147395...,Mokuj1n,Roman Petrushenko,20812.81,CS 2,NaN,NaN,2025,9302.81,2024,11510.00,0.45,0.55,Russian Federation
3796,297,https://www.esportsearnings.com/players/39366-...,The eLiVe,Erik Sith,20645.39,CS 2,NaN,NaN,2025,4200.00,2024,7043.69,0.20,0.34,Slovakia
3797,298,https://www.esportsearnings.com/players/15158-...,kaze,Andrew Khong Weng Keong,20448.93,CS 2,30.00,30.00,2025,7027.60,2024,9428.04,0.34,0.46,Malaysia
3798,299,https://www.esportsearnings.com/players/53074-...,phzy,Love Smidebrant,20320.30,CS 2,NaN,NaN,2025,10600.00,2024,9720.30,0.52,0.48,Sweden
3799,300,https://www.esportsearnings.com/players/16800-...,Stewie2k,Jakey Yip,20285.71,CS 2,27.00,26.00,2024,20000.00,2023,285.71,0.99,0.01,United States

In [ ]:
df_player_clean = df_player_clean[~df_player_clean['game'].str.contains('CS: GO', case=False, na=False)]

In [ ]:
df_player_clean.isnull().sum()

rank                            0
url_player                      0
pseudo_player                   0
surname_name                    0
total_cash_prize                0
game                            0
age                          1586
age_during_game              1586
last_year_pro_date              0
last_year_earnings              0
year_before_last               75
year_before_last_earnings       1
last_year_to_total              0
year_before_to_total            0
country_full                    0
dtype: int64

In [ ]:
df_player_clean.describe()

,rank,total_cash_prize,age,age_during_game,last_year_pro_date,last_year_earnings,year_before_last_earnings,last_year_to_total,year_before_to_total
count,3800.00,3800.00,2214.00,2214.00,3800.00,3800.00,3799.00,3800.00,3800.00
mean,242.61,188283.93,25.36,23.74,2023.06,16197.09,33237.12,0.20,0.32
std,143.22,500552.74,4.25,3.53,2.13,35773.11,69761.03,0.32,0.31
min,1.00,6342.99,15.00,15.00,2012.00,0.00,0.00,0.00,0.00
25%,119.00,23156.76,22.00,21.00,2022.00,1525.34,4000.00,0.02,0.07
50%,238.00,61464.94,25.00,23.00,2024.00,4843.11,10845.78,0.08,0.22
75%,365.00,143411.76,28.00,26.00,2025.00,13933.09,32000.00,0.26,0.48
max,500.00,7172436.83,40.00,39.00,2025.00,640485.00,1180543.33,8.30,3.77

In [ ]:
unique_players = df_player_clean['pseudo_player'].nunique()
print(f"Number of unique players: {unique_players}")

Number of unique players: 3725

# **Filter By The Active players in 2024 - 2025**

In [ ]:
# Filter for players active in 2024 or 2025
df_filter = df_player_clean[
    (df_player_clean['last_year_pro_date'].isin([2024, 2025])) &
    (df_player_clean['year_before_last'] == 2024) &
    (df_player_clean['game'].notna())
]

# View relevant columns (optional: adjust the columns as needed)
df_filter = df_filter[['rank','country_full','pseudo_player','total_cash_prize','game', 'last_year_pro_date', 'year_before_last_earnings','year_before_last']]
df_filter

,rank,country_full,pseudo_player,total_cash_prize,game,last_year_pro_date,year_before_last_earnings,year_before_last
3,4,Russian Federation,Miposhka,6011771.49,Dota 2,2025,247319.40,2024
4,5,France,Ceb,5949442.73,Dota 2,2025,58500.00,2024
6,7,Russian Federation,Collapse,5724111.07,Dota 2,2025,194319.40,2024
7,8,Ukraine,Yatoro,5716736.05,Dota 2,2025,183182.50,2024
8,9,Ukraine,Mira,5593899.05,Dota 2,2025,182319.40,2024
...,...,...,...,...,...,...,...,...
3794,295,Russian Federation,Krad,20932.32,CS 2,2025,14700.00,2024
3795,296,Russian Federation,Mokuj1n,20812.81,CS 2,2025,11510.00,2024
3796,297,Slovakia,The eLiVe,20645.39,CS 2,2025,7043.69,2024
3797,298,Malaysia,kaze,20448.93,CS 2,2025,9428.04,2024
3798,299,Sweden,phzy,20320.30,CS 2,2025,9720.30,2024

# **Top coutries by total cash prize for all the games**

In [ ]:
country_cash_prize = df_player_clean.groupby('country_full')['total_cash_prize'].sum().reset_index()

# Sort values for better visual
country_cash_prize = country_cash_prize.sort_values(by='total_cash_prize', ascending=False)

# Create bar chart
fig = px.bar(
    country_cash_prize,
    x='country_full',
    y='total_cash_prize',
    title='Total Cash Prize by Country',
    labels={'country_full': 'Country', 'total_cash_prize': 'Total Cash Prize ($)'},
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

# **Top 10 Countries by Total Cash Prize**

In [ ]:
country_cash_prize = df_player_clean.groupby('country_full')['total_cash_prize'].sum().reset_index()

# Convert cash prize to numeric if needed
country_cash_prize['total_cash_prize'] = pd.to_numeric(country_cash_prize['total_cash_prize'], errors='coerce')

# Drop NaNs
country_cash_prize = country_cash_prize.dropna(subset=['total_cash_prize'])

# Get top 10 countries
top10_countries = country_cash_prize.nlargest(10, 'total_cash_prize')

# Create bar chart
fig = px.bar(
    top10_countries,
    x='country_full',
    y='total_cash_prize',
    title='Top 10 Countries by Total Cash Prize',
    labels={'country_full': 'Country', 'total_cash_prize': 'Total Cash Prize ($)'},
    text_auto='.2s'  # Short format text on bars (e.g., 1M, 500K)
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

# **Count players per country**

In [ ]:
# Count players per country
players_per_country = df_player_clean['country_full'].value_counts().reset_index()
players_per_country.columns = ['country', 'player_count']

# Optional: Show top 20 countries only
top_countries = players_per_country.nlargest(20, 'player_count')

# Create bar chart
fig = px.bar(
    top_countries,
    x='country',
    y='player_count',
    title='Number of Players per Country',
    labels={'country': 'Country', 'player_count': 'Number of Players'},
    text_auto=True
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [ ]:
df_player_clean

,rank,url_player,pseudo_player,surname_name,total_cash_prize,game,age,age_during_game,last_year_pro_date,last_year_earnings,year_before_last,year_before_last_earnings,last_year_to_total,year_before_to_total,country_full
0,1,https://www.esportsearnings.com/players/3304-n...,N0tail,Johan Sundstein,7172436.83,Dota 2,31.00,27.00,2021,214100.00,2020,75571.40,0.03,0.01,Denmark
1,2,https://www.esportsearnings.com/players/3822-j...,JerAx,Jesse Vainikka,6486075.22,Dota 2,33.00,30.00,2022,16400.00,2020,548.76,0.00,0.00,Finland
2,3,https://www.esportsearnings.com/players/30451-...,ana,Anathan Pham,6024411.96,Dota 2,25.00,22.00,2022,20000.00,2021,4000.00,0.00,0.00,Australia
3,4,https://www.esportsearnings.com/players/15855-...,Miposhka,Yaroslav Naidenov,6011771.49,Dota 2,27.00,27.00,2025,135000.00,2024,247319.40,0.02,0.04,Russian Federation
4,5,https://www.esportsearnings.com/players/2811-c...,Ceb,SÃ©bastien Debs,5949442.73,Dota 2,33.00,33.00,2025,3600.00,2024,58500.00,0.00,0.01,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,296,https://www.esportsearnings.com/players/147395...,Mokuj1n,Roman Petrushenko,20812.81,CS 2,NaN,NaN,2025,9302.81,2024,11510.00,0.45,0.55,Russian Federation
3796,297,https://www.esportsearnings.com/players/39366-...,The eLiVe,Erik Sith,20645.39,CS 2,NaN,NaN,2025,4200.00,2024,7043.69,0.20,0.34,Slovakia
3797,298,https://www.esportsearnings.com/players/15158-...,kaze,Andrew Khong Weng Keong,20448.93,CS 2,30.00,30.00,2025,7027.60,2024,9428.04,0.34,0.46,Malaysia
3798,299,https://www.esportsearnings.com/players/53074-...,phzy,Love Smidebrant,20320.30,CS 2,NaN,NaN,2025,10600.00,2024,9720.30,0.52,0.48,Sweden
3799,300,https://www.esportsearnings.com/players/16800-...,Stewie2k,Jakey Yip,20285.71,CS 2,27.00,26.00,2024,20000.00,2023,285.71,0.99,0.01,United States

**New Data Frame updated and cleaned**

In [ ]:
df_player_clean['combined'] = df_player_clean['pseudo_player'].astype(str) +  ' - ' + df_player_clean['surname_name'].astype(str) + ' - ' +  df_player_clean['game'].astype(str)

# Preview the result
df_player_clean[['pseudo_player', 'rank', 'game', 'combined']].head()

  pseudo_player  rank    game                               combined
0        N0tail     1  Dota 2      N0tail - Johan Sundstein - Dota 2
1         JerAx     2  Dota 2        JerAx - Jesse Vainikka - Dota 2
2           ana     3  Dota 2            ana - Anathan Pham - Dota 2
3      Miposhka     4  Dota 2  Miposhka - Yaroslav Naidenov - Dota 2
4           Ceb     5  Dota 2         Ceb - SÃ©bastien Debs - Dota 2

In [ ]:
unique_players = df_player_clean['combined'].nunique()
print(f"Number of unique players: {unique_players}")

Number of unique players: 3799

In [ ]:
df_grouped = df_player_clean.groupby('combined').agg({
    'rank': 'first',
    'url_player': 'first',
    'surname_name': 'first',
    'total_cash_prize': 'sum',
    'game': lambda x: ', '.join(x.dropna().astype(str).unique()),
    'age': 'first',
    'age_during_game': 'first',
    'last_year_pro_date': 'max',
    'last_year_earnings': 'sum',
    'year_before_last': 'max',
    'year_before_last_earnings': 'sum',
    'last_year_to_total': 'first',
    'year_before_to_total': 'first',
    'country_full': 'first'
}).reset_index()

In [ ]:
df_player_clean.drop(columns=['surname_name'], inplace=True)

In [ ]:
df_player_clean

,rank,url_player,pseudo_player,total_cash_prize,game,age,age_during_game,last_year_pro_date,last_year_earnings,year_before_last,year_before_last_earnings,last_year_to_total,year_before_to_total,country_full,combined
0,1,https://www.esportsearnings.com/players/3304-n...,N0tail,7172436.83,Dota 2,31.00,27.00,2021,214100.00,2020,75571.40,0.03,0.01,Denmark,N0tail - Johan Sundstein - Dota 2
1,2,https://www.esportsearnings.com/players/3822-j...,JerAx,6486075.22,Dota 2,33.00,30.00,2022,16400.00,2020,548.76,0.00,0.00,Finland,JerAx - Jesse Vainikka - Dota 2
2,3,https://www.esportsearnings.com/players/30451-...,ana,6024411.96,Dota 2,25.00,22.00,2022,20000.00,2021,4000.00,0.00,0.00,Australia,ana - Anathan Pham - Dota 2
3,4,https://www.esportsearnings.com/players/15855-...,Miposhka,6011771.49,Dota 2,27.00,27.00,2025,135000.00,2024,247319.40,0.02,0.04,Russian Federation,Miposhka - Yaroslav Naidenov - Dota 2
4,5,https://www.esportsearnings.com/players/2811-c...,Ceb,5949442.73,Dota 2,33.00,33.00,2025,3600.00,2024,58500.00,0.00,0.01,France,Ceb - SÃ©bastien Debs - Dota 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,296,https://www.esportsearnings.com/players/147395...,Mokuj1n,20812.81,CS 2,NaN,NaN,2025,9302.81,2024,11510.00,0.45,0.55,Russian Federation,Mokuj1n - Roman Petrushenko - CS 2
3796,297,https://www.esportsearnings.com/players/39366-...,The eLiVe,20645.39,CS 2,NaN,NaN,2025,4200.00,2024,7043.69,0.20,0.34,Slovakia,The eLiVe - Erik Sith - CS 2
3797,298,https://www.esportsearnings.com/players/15158-...,kaze,20448.93,CS 2,30.00,30.00,2025,7027.60,2024,9428.04,0.34,0.46,Malaysia,kaze - Andrew Khong Weng Keong - CS 2
3798,299,https://www.esportsearnings.com/players/53074-...,phzy,20320.30,CS 2,NaN,NaN,2025,10600.00,2024,9720.30,0.52,0.48,Sweden,phzy - Love Smidebrant - CS 2
3799,300,https://www.esportsearnings.com/players/16800-...,Stewie2k,20285.71,CS 2,27.00,26.00,2024,20000.00,2023,285.71,0.99,0.01,United States,Stewie2k - Jakey Yip - CS 2

# **Math Aggregation for Player Database Clean**

In [ ]:
df_player_clean.describe()

,rank,total_cash_prize,age,age_during_game,last_year_pro_date,last_year_earnings,year_before_last_earnings,last_year_to_total,year_before_to_total
count,3800.00,3800.00,2214.00,2214.00,3800.00,3800.00,3799.00,3800.00,3800.00
mean,242.61,188283.93,25.36,23.74,2023.06,16197.09,33237.12,0.20,0.32
std,143.22,500552.74,4.25,3.53,2.13,35773.11,69761.03,0.32,0.31
min,1.00,6342.99,15.00,15.00,2012.00,0.00,0.00,0.00,0.00
25%,119.00,23156.76,22.00,21.00,2022.00,1525.34,4000.00,0.02,0.07
50%,238.00,61464.94,25.00,23.00,2024.00,4843.11,10845.78,0.08,0.22
75%,365.00,143411.76,28.00,26.00,2025.00,13933.09,32000.00,0.26,0.48
max,500.00,7172436.83,40.00,39.00,2025.00,640485.00,1180543.33,8.30,3.77

# **Variation of Player Ages by Game**

In [ ]:
# Make sure age column is numeric
df_player_clean['age_during_game'] = pd.to_numeric(df_player_clean['age_during_game'], errors='coerce')

# Drop rows with missing age or game
df_age = df_player_clean.dropna(subset=['age_during_game', 'game'])

# Group by game and age to count players
age_distribution = df_age.groupby(['game', 'age_during_game'])['combined'].count().reset_index()
age_distribution.rename(columns={'combined': 'num_players'}, inplace=True)

# Plot as a line chart
fig = px.line(
    age_distribution,
    x='age_during_game',
    y='num_players',
    color='game',
    markers=True,
    title='Variation of Player Ages by Game',
    labels={'age_during_game': 'Age', 'num_players': 'Number of Players'}
)

fig.update_layout(xaxis=dict(dtick=1))  # Show each age
fig.show()

# **Mean Age of Players by Game**

In [ ]:
df_player_clean['age_durnig_game'] = pd.to_numeric(df_player_clean['age_during_game'], errors='coerce')

# Drop rows with missing values in 'age' or 'game'
df_age_clean = df_player_clean.dropna(subset=['age_during_game', 'game'])

# Group by game and calculate the mean age
mean_age_per_game = df_age_clean.groupby('game')['age_during_game'].mean().reset_index()

# Sort by mean age (ascending)
mean_age_per_game = mean_age_per_game.sort_values(by='age_during_game', ascending=True)

# Create the bar chart
fig = px.bar(
    mean_age_per_game,
    x='game',
    y='age_during_game',
    title='Mean Age of Players by Game',
    labels={'game': 'Game', 'age_during_game': 'Mean Age'},
    text_auto='.2f'
)

# Set y-axis range
fig.update_layout(
    yaxis=dict(range=[20, 30]),
    xaxis_tickangle=-45)
fig.show()

# **Group by country and calculate total cash prize**

In [ ]:
# Group by country and calculate total cash prize
total_cash_by_country = df_player_clean.groupby('country_full')['total_cash_prize'].sum()

# Group by country and count the number of players
total_players_by_country = df_player_clean.groupby('country_full')['combined'].count()

# Combine both into a single DataFrame
cash_per_player = (total_cash_by_country / total_players_by_country).reset_index()
cash_per_player.columns = ['country_full', 'cash_prize_per_player']

# Optional: Sort values
cash_per_player = cash_per_player.sort_values(by='cash_prize_per_player', ascending=False)

# Show top 10 countries (optional)
cash_per_player.head(50)

                        country_full  cash_prize_per_player
51                             Macao             1336593.81
63                          Pakistan             1208118.36
54              Moldova, Republic of             1145106.81
61                   North Macedonia              945797.35
41                            Jordan              873768.44
23                           Estonia              862659.46
10                          Bulgaria              811166.53
1                            Armenia              776529.72
38                            Israel              775916.48
48                           Lebanon              651938.34
24                           Finland              528796.33
3                            Austria              489186.16
91                        Uzbekistan              482976.85
76                          Slovakia              474430.27
52                          Malaysia              451643.92
86                           Ukraine              430199.00
14                             China              411403.82
45                        Kyrgyzstan              389809.04
47                            Latvia              309289.69
80                            Sweden              300882.86
7    Bolivia, Plurinational State of              296957.99
71                Russian Federation              293463.48
77                          Slovenia              291746.64
20                           Denmark              286922.74
74                            Serbia              262352.46
11                          Cambodia              261065.91
29                         Guatemala              246791.67
70                           Romania              246406.83
62                            Norway              231969.41
46  Lao People's Democratic Republic              221564.06
66                       Philippines              218943.18
57                           Morocco              209664.47
65                              Peru              206110.36
30                         Hong Kong              196243.27
58                       Netherlands              194245.78
27                           Germany              191746.00
67                            Poland              191304.57
8             Bosnia and Herzegovina              189498.06
12                            Canada              183105.65
25                            France              182762.30
43                Korea, Republic of              178704.13
17                           Croatia              172660.80
81                       Switzerland              169355.26
55                          Mongolia              146792.57
75                         Singapore              141020.32
89                     United States              140245.95
2                          Australia              136794.96
18                              Cuba              131155.00
28                            Greece              130770.82
6                            Belgium              127751.58

In [ ]:
total_cash_by_country = df_player_clean.groupby('country_full')['total_cash_prize'].sum()

# Group by country and count the number of players
total_players_by_country = df_player_clean.groupby('country_full')['combined'].count()

# Filter only countries with 50 or more players
valid_countries = total_players_by_country[total_players_by_country >= 50].index

# Filter both Series using the valid countries
filtered_cash = total_cash_by_country[valid_countries]
filtered_players = total_players_by_country[valid_countries]

# Calculate cash prize per player
cash_per_player = (filtered_cash / filtered_players).reset_index()
cash_per_player.columns = ['country_full', 'cash_prize_per_player']

# Sort values descending
cash_per_player = cash_per_player.sort_values(by='cash_prize_per_player', ascending=False)

# Display result
cash_per_player.head(50)

                 country_full  cash_prize_per_player
17                    Ukraine              430199.00
3                       China              411403.82
13                     Sweden              300882.86
11         Russian Federation              293463.48
4                     Denmark              286922.74
9                 Philippines              218943.18
6                     Germany              191746.00
10                     Poland              191304.57
2                      Canada              183105.65
5                      France              182762.30
8          Korea, Republic of              178704.13
19              United States              140245.95
0                   Australia              136794.96
18             United Kingdom              115389.31
1                      Brazil               97225.51
14  Taiwan, Province of China               92557.05
15                   Thailand               75275.09
12               Saudi Arabia               69648.20
16                    Türkiye               59629.50
7                       Japan               46056.80

In [ ]:
fig = px.bar(
    cash_per_player,
    x='country_full',
    y='cash_prize_per_player',
    title='Avg Cash Prize per Player by Country (Only Countries with ≥50 Players)',
    labels={'country_full': 'Country', 'cash_prize_per_player': 'Cash Prize per Player ($)'},
    text_auto=True
)
fig.update_layout( yaxis=dict(range=[20000, 500000]), xaxis_tickangle=-45)
fig.show()